# Homebrew formula for the lore CLI.
# Auto-generated by update-homebrew.yml — do not edit by hand.
#
# To install:
#   brew tap Gasmanc/lore
#   brew install lore

class Lore < Formula
  desc "Local documentation server for AI coding assistants"
  homepage "https://github.com/Gasmanc/lore"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Gasmanc/lore/releases/download/v0.2.1/lore-v0.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "393fb2b294e386a78027f50c0ef7473a8279497e7b2351619b224f8b1d46fb93"
    end

    on_intel do
      url "https://github.com/Gasmanc/lore/releases/download/v0.2.1/lore-v0.2.1-x86_64-apple-darwin.tar.gz"
      sha256 "5d016cf307bc38c234b31029d99cf3a5b01952816f7ac946bc7eaa25ead8a21e"
    end
  end

  on_linux do
    on_arm do
      odie "Pre-built aarch64 Linux binary not available yet. Install with: cargo install lore-cli"
    end

    on_intel do
      url "https://github.com/Gasmanc/lore/releases/download/v0.2.1/lore-v0.2.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c4536a35b1691061e4e10127e7a75fafa755e485bedfcecfa40875ae51c30e24"
    end
  end

  def install
    bin.install "lore"
  end

  def caveats
    <<~EOS
      The first time lore downloads a package it will fetch the bge-small-en-v1.5
      embedding model (~130 MB) and cache it in:
        ~/.cache/lore/models/

      To get started, add a documentation package:
        lore add tokio

      Then configure your AI assistant to use the MCP server:
        lore mcp
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lore --version")
  end
end
