# Homebrew formula for the lore CLI.
# Auto-generated by update-homebrew.yml — do not edit by hand.
#
# To install:
#   brew tap Gasmanc/lore
#   brew install lore

class Lore < Formula
  desc "Local documentation server for AI coding assistants"
  homepage "https://github.com/Gasmanc/lore"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Gasmanc/lore/releases/download/v0.2.0/lore-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "b87b116ca133e2aff0d24eca188652b58d858ab771f6b67a461f2eefbbb30ed3"
    end

    on_intel do
      url "https://github.com/Gasmanc/lore/releases/download/v0.2.0/lore-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "d329ec43c557f4ea8a6186a60c8811ed6066641720517583560110660d1bb9f3"
    end
  end

  on_linux do
    on_arm do
      # aarch64-linux binary is not yet available; install via cargo instead:
      #   cargo install lore-cli
      odie "Pre-built aarch64 Linux binary not available yet. Install with: cargo install lore-cli"
    end

    on_intel do
      url "https://github.com/Gasmanc/lore/releases/download/v0.2.0/lore-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "dc4e3e574433c56ab416c1aab50d41ccadcb224f4855d3d59d1536747a673f23"
    end
  end

  def install
    bin.install "lore"
  end

  def caveats
    <<~EOS
      The first time lore downloads a package it will fetch the bge-small-en-v1.5
      embedding model (~130 MB) and cache it in:
        ~/.cache/lore/models/

      To get started, add a documentation package:
        lore add tokio

      Then configure your AI assistant to use the MCP server:
        lore mcp
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lore --version")
  end
end
