# Homebrew formula for the lore CLI.
# Auto-generated by update-homebrew.yml — do not edit by hand.
#
# To install:
#   brew tap Gasmanc/lore
#   brew install lore

class Lore < Formula
  desc "Local documentation server for AI coding assistants"
  homepage "https://github.com/Gasmanc/lore"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Gasmanc/lore/releases/download/v0.1.0/lore-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "ba96b02abb7eaf08dd6a6762dc579e5439fde9daba19f66ac3cb72aa87093917"
    end

    on_intel do
      url "https://github.com/Gasmanc/lore/releases/download/v0.1.0/lore-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "efa5b100b6a2d65d710723622717cd7c7b2a4a45e6a27dbbdbf6e9ab11bc2b67"
    end
  end

  on_linux do
    on_arm do
      # aarch64-linux binary is not yet available; install via cargo instead:
      #   cargo install lore-cli
      odie "Pre-built aarch64 Linux binary not available yet. Install with: cargo install lore-cli"
    end

    on_intel do
      url "https://github.com/Gasmanc/lore/releases/download/v0.1.0/lore-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f58db7f1cc5581a74ae741c5acd852378e21b7db62c67c1329d6b0719886bafe"
    end
  end

  def install
    bin.install "lore"
  end

  def caveats
    <<~EOS
      The first time lore downloads a package it will fetch the bge-small-en-v1.5
      embedding model (~130 MB) and cache it in:
        ~/.cache/lore/models/

      To get started, add a documentation package:
        lore add tokio

      Then configure your AI assistant to use the MCP server:
        lore mcp
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lore --version")
  end
end
